name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dfinity/setup-dfx@v0.2.1
        with:
          dfx-version: 0.17.0
      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: install mops packages
        run: mops install

      - name: run tests
        run: mops test